# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20190505_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
