# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20190505_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
