# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20190505_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tutorial',
            field=models.TextField(blank=True),
        ),
    ]
