# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_product_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aliexpress_url',
            field=models.URLField(blank=True),
        ),
    ]
