# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_product_aliexpress_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=1.3, editable=False, null=True, verbose_name='Rating'),
        ),
    ]
