# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20190601_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=5, editable=False, null=True, verbose_name='Rating'),
        ),
    ]
