# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_is_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_md',
        ),
    ]
