# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_is_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, height_field=353, upload_to=b'', verbose_name='image', width_field=1000),
            preserve_default=False,
        ),
    ]
