# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'HTML'), (3, 'HOT'), (4, 'Latest Comment'), (2, 'Latest Article')], default=1, verbose_name='display type'),
        ),
    ]
