# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20190527_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'HTML'), (3, 'Featured Articles'), (4, 'Latest Comments'), (2, 'Latest Articles'), (5, 'Popular Tags')], default=1, verbose_name='display type'),
        ),
    ]
